<?php

namespace PHPMailchimp;

class Error
{
    /**
     * An absolute URI that identifies the problem type. When dereferenced, it should provide human-readable documentation for the problem type.
     * Title: Problem Type
     * Type: String
     * @var string $type
     *
     * @PHPMailchimp\Annotations\Required
     */
    public $type;

    /**
     * A short, human-readable summary of the problem type. It shouldn’t change based on the occurrence of the problem, except for purposes of localization.
     * Title: Error Title
     * Type: String
     * @var string $title
     *
     * @PHPMailchimp\Annotations\Required
     */
    public $title;

    /**
     * The HTTP status code (RFC2616, Section 6) generated by the origin server for this occurrence of the problem.
     * Title: HTTP Status Code
     * Type: Integer
     * @var int $status
     */
    public $status;

    /**
     * A human-readable explanation specific to this occurrence of the problem. Learn more about errors.
     * https://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/#errors
     * Title: Error Message
     * Type: String
     * @var string $detail
     *
     * @PHPMailchimp\Annotations\Required
     */
    public $detail;

    /**
     * A string that identifies this specific occurrence of the problem. Please provide this ID when contacting support.
     * Title: Instance ID
     * Type: String
     * @var string $instance
     *
     * @PHPMailchimp\Annotations\Required
     */
    public $instance;

    /**
     * @var array $errors
     */
    public $errors;
}